---
- name: Install Apache httpd 
  hosts: all
  user: mowings
  sudo: yes
  tasks:
  - name: install httpd pacakge
    action: yum pkg=httpd state=installed
  - name: start Apache
    action: service name=httpd state=started enabled=true
