---
- name: Update to latest packages
  hosts: all
  user: root
  tasks:
  - name: update all packages
    action: yum pkg=* state=latest
    notify: reboot
  - handler: reboot
    shell: shutdown -r now
